---
- name: Run the Ginflix application on the Telecom remote server
  hosts: telecom
  gather_facts: false
  become: false

  tasks:
    - name: Get the GitHub repository
      shell: |
        cd ~
        git clone https://github.com/gara2000/ginflix.git
    
    - name: Create the K8s cluster
      shell: |
        cd ~/ginflix
        make cluster-create

    - name: Stop the application if it was previously running
      shell: |
        cd ~/ginflix
        make stop
      ignore_errors: true

    - name: Start the application
      shell: |
        cd ~/ginflix
        make start

    - name: Copy the video inside the streamer
      shell: |
        cd ~/ginflix
        make copy